module.exports.config = {
	name: "gái",
	version: "1.0.0",
	hasPermssion: 0,
	credits: "ThienNhan",
	description: "Random ảnh gái xinh nhất Việt Nam :))",
	commandCategory: "random-img",
	usages: "gái",
  cooldowns: 5,
  dependencies: {
    "request":"",
    "fs-extra":"",
    "axios":""
  }
    
};

module.exports.run = async({api,event,args,Users,Threads,Currencies}) => {
const axios = global.nodemodule["axios"];
const request = global.nodemodule["request"];
const fs = global.nodemodule["fs-extra"];
	var link = [
"https://api.thoikhoabieu.ml/gai/1.jpg",
"https://api.thoikhoabieu.ml/gai/2.jpg",
"https://api.thoikhoabieu.ml/gai/3.jpg",
"https://api.thoikhoabieu.ml/gai/4.jpg",
"https://api.thoikhoabieu.ml/gai/5.jpg",
"https://api.thoikhoabieu.ml/gai/6.jpg",
"https://api.thoikhoabieu.ml/gai/7.jpg",
"https://api.thoikhoabieu.ml/gai/8.jpg",
"https://api.thoikhoabieu.ml/gai/9.jpg",
"https://api.thoikhoabieu.ml/gai/10.jpg",
"https://api.thoikhoabieu.ml/gai/11.jpg",
"https://api.thoikhoabieu.ml/gai/12.jpg",
"https://api.thoikhoabieu.ml/gai/13.jpg",
"https://api.thoikhoabieu.ml/gai/14.jpg",
"https://api.thoikhoabieu.ml/gai/15.jpg",
"https://api.thoikhoabieu.ml/gai/16.jpg",
"https://api.thoikhoabieu.ml/gai/17.jpg",
"https://api.thoikhoabieu.ml/gai/18.jpg",
"https://api.thoikhoabieu.ml/gai/19.jpg",
"https://api.thoikhoabieu.ml/gai/20.jpg",
"https://api.thoikhoabieu.ml/gai/21.jpg",
"https://api.thoikhoabieu.ml/gai/22.jpg",
"https://api.thoikhoabieu.ml/gai/23.jpg",
"https://api.thoikhoabieu.ml/gai/24.jpg",
"https://api.thoikhoabieu.ml/gai/25.jpg",
"https://api.thoikhoabieu.ml/gai/26.jpg",
"https://api.thoikhoabieu.ml/gai/27.jpg",
"https://api.thoikhoabieu.ml/gai/28.jpg",
"https://api.thoikhoabieu.ml/gai/29.jpg",
"https://api.thoikhoabieu.ml/gai/30.jpg",
"https://api.thoikhoabieu.ml/gai/31.jpg",
"https://api.thoikhoabieu.ml/gai/32.jpg",
"https://api.thoikhoabieu.ml/gai/33.jpg",
"https://api.thoikhoabieu.ml/gai/34.jpg",
"https://api.thoikhoabieu.ml/gai/35.jpg",
"https://api.thoikhoabieu.ml/gai/36.jpg",
"https://api.thoikhoabieu.ml/gai/37.jpg",
"https://api.thoikhoabieu.ml/gai/38.jpg",
"https://api.thoikhoabieu.ml/gai/39.jpg",
"https://api.thoikhoabieu.ml/gai/40.jpg",
"https://api.thoikhoabieu.ml/gai/41.jpg",
"https://api.thoikhoabieu.ml/gai/42.jpg",
"https://api.thoikhoabieu.ml/gai/43.jpg",
"https://api.thoikhoabieu.ml/gai/44.jpg",
"https://api.thoikhoabieu.ml/gai/45.jpg",
"https://api.thoikhoabieu.ml/gai/46.jpg",
"https://api.thoikhoabieu.ml/gai/47.jpg",
"https://api.thoikhoabieu.ml/gai/48.jpg",
"https://api.thoikhoabieu.ml/gai/49.jpg",
"https://api.thoikhoabieu.ml/gai/50.jpg",
"https://api.thoikhoabieu.ml/gai/51.jpg",
"https://api.thoikhoabieu.ml/gai/52.jpg",
"https://api.thoikhoabieu.ml/gai/53.jpg",
"https://api.thoikhoabieu.ml/gai/54.jpg",
"https://api.thoikhoabieu.ml/gai/55.jpg",
"https://api.thoikhoabieu.ml/gai/56.jpg",
"https://api.thoikhoabieu.ml/gai/57.jpg",
"https://api.thoikhoabieu.ml/gai/58.jpg",
"https://api.thoikhoabieu.ml/gai/59.jpg",
"https://api.thoikhoabieu.ml/gai/60.jpg",
"https://api.thoikhoabieu.ml/gai/61.jpg",
"https://api.thoikhoabieu.ml/gai/62.jpg",
"https://api.thoikhoabieu.ml/gai/63.jpg",
"https://api.thoikhoabieu.ml/gai/64.jpg",
"https://api.thoikhoabieu.ml/gai/65.jpg",
"https://api.thoikhoabieu.ml/gai/66.jpg",
"https://api.thoikhoabieu.ml/gai/67.jpg",
"https://api.thoikhoabieu.ml/gai/68.jpg",
"https://api.thoikhoabieu.ml/gai/69.jpg",
"https://api.thoikhoabieu.ml/gai/70.jpg",
"https://api.thoikhoabieu.ml/gai/71.jpg",
"https://api.thoikhoabieu.ml/gai/72.jpg",
"https://api.thoikhoabieu.ml/gai/73.jpg",
"https://api.thoikhoabieu.ml/gai/74.jpg",
"https://api.thoikhoabieu.ml/gai/75.jpg",
"https://api.thoikhoabieu.ml/gai/76.jpg",
"https://api.thoikhoabieu.ml/gai/77.jpg",
"https://api.thoikhoabieu.ml/gai/78.jpg",
"https://api.thoikhoabieu.ml/gai/79.jpg",
"https://api.thoikhoabieu.ml/gai/80.jpg",
"https://api.thoikhoabieu.ml/gai/81.jpg",
"https://api.thoikhoabieu.ml/gai/82.jpg",
"https://api.thoikhoabieu.ml/gai/83.jpg",
];
	 var callback = () => api.sendMessage({body:`Chúc mừng, đây là ảnh gái dành cho bạn\nSố ảnh hiện có: ${link.length}`,attachment: fs.createReadStream(__dirname + "/cache/1.jpg")}, event.threadID, () => fs.unlinkSync(__dirname + "/cache/1.jpg"));	
      return request(encodeURI(link[Math.floor(Math.random() * link.length)])).pipe(fs.createWriteStream(__dirname+"/cache/1.jpg")).on("close",() => callback());
   };